name: Build and Deploy

on:
  push:
    branches:
      - desenv
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '12.x'
    - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Build
      run: |
        npm install
      #npm run-script deploy
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        #FOLDER: dist/edualcantara.dev



# name: Build & Deploy

# on:
#   push:
#     paths-ignore:
#       - "**.md"
#     branches:
#       - hotfix/*
#       - release
#   pull_request:
#     branches:
#       - develop
#   workflow_dispatch:
#     inputs:
#       name:
#         description: 'Person'
#         required: true

# jobs:
#   build:
#     name: build
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [12.x]

#     steps:
#       - uses: actions/checkout@v2
#       - name: use node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - run: npm install
#       - run: npm run build
#       - name: docker build & push
#         uses: docker/build-push-action@v1.1.0
#         with:
#           username: lennonalvesdias
#           password: ${{ secrets.GITHUB_TOKEN }}
#           repository: lennonalvesdias/lennonalvesdias.github.io/site
#           registry: docker.pkg.github.com
#           tags: ${{ github.sha }}, latest
#           dockerfile: Dockerfile

  # Deploy para VM
  # deploy:
  #   name: deploy
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: docker deploy
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST_ADDRESS }}
  #         username: ${{ secrets.HOST_USERNAME }}
  #         password: ${{ secrets.HOST_PASSWORD }}
  #         script: |
  #           cat ./github_token.txt | docker login docker.pkg.github.com -u lennonalvesdias --password-stdin
  #           docker pull docker.pkg.github.com/lennonalvesdias/lennonalvesdias.github.io/site:latest
  #           docker rm -f site || true
  #           docker run -d --name site -p 1994:80 --restart=always --net nginx-proxy -e VIRTUAL_HOST=site.lennon.cloud,lennon.cloud -e LETSENCRYPT_HOST=site.lennon.cloud,lennon.cloud -e LETSENCRYPT_EMAIL=lennonalvesdias@gmail.com docker.pkg.github.com/lennonalvesdias/lennonalvesdias.github.io/site:latest

